import { Project } from "../types/portfolio";

export const PORTFOLIO_PROJECTS: Project[] = [
  {
    id: "meachery-furniture",
    number: "01",
    name: "Meachery Furniture",
    category: "Furniture E-Commerce",
    industry: "E-Commerce & Interior",
    description: "Premium wooden furniture and modern interior design items.",
    longDescription: "A high-performance modern web storefront for handcrafted luxury wood items and modern home decoration. Connects instant cart overlays, filter search bars, grid layouts, product reviews, and custom checkouts.",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Redux", "Stripe API"],
    liveUrl: "https://www.meacheryfurniture.in",
    caseStudyUrl: "#",
    mockLayoutType: "ecommerce"
  },
  {
    id: "the-consultant-7",
    number: "02",
    name: "The Consultant 7",
    category: "Consulting Portal",
    industry: "Corporate Advisory",
    description: "Expert business advisory, management consulting & analytics.",
    longDescription: "An advanced business intelligence dashboard showing client operations overview, consulting analytics, system logs, active advisors tracker, and interactive financial progress charts.",
    technologies: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Recharts", "Zustand"],
    liveUrl: "https://www.theconsultant7.in",
    caseStudyUrl: "#",
    mockLayoutType: "dashboard"
  },
  {
    id: "shq-life",
    number: "03",
    name: "SHQ Life",
    category: "Fitness & Nutrition Portal",
    industry: "Gym & Health Coaching",
    description: "Personalized lifestyle coaching, diets, and training schedules.",
    longDescription: "A bold, energetic workout portal for fitness brands. Includes customized trainer calendars, online membership signups, and training plan configurators.",
    technologies: ["Next.js", "Tailwind CSS", "Framer Motion", "Supabase"],
    liveUrl: "https://www.shq.life/",
    caseStudyUrl: "#",
    mockLayoutType: "gym"
  },
  {
    id: "safeguard-homeshifters",
    number: "04",
    name: "Safeguard Shifters",
    category: "Logistics Platform",
    industry: "Logistics & Transport",
    description: "Hassle-free packers, movers and cargo shipping services.",
    longDescription: "A high-end corporate presence built for enterprise transport logistics. Features full service grids, price calculators, dynamic tracking sections, and custom lead acquisition funnels designed to increase client conversions.",
    technologies: ["React", "TypeScript", "Tailwind CSS", "Node.js", "Express"],
    liveUrl: "https://www.safeguardhomeshifters.in",
    caseStudyUrl: "#",
    mockLayoutType: "corporate"
  },
  {
    id: "flawless-era",
    number: "05",
    name: "Flawless Era Store",
    category: "Apparel & Lifestyle",
    industry: "Fashion E-Commerce",
    description: "Elevate your style with curated beauty and seasonal fashion.",
    longDescription: "A cinematic lookbook and digital store for luxury fashion. Features immersive video backdrops, smooth infinite collection swiping, and product-focused grid systems.",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "GSAP ScrollTrigger"],
    liveUrl: "https://flawlessera.store/",
    caseStudyUrl: "#",
    mockLayoutType: "fashion"
  },
  {
    id: "mars-media",
    number: "06",
    name: "Mars Media Studio",
    category: "Production Portfolio",
    industry: "Cinematography & Media",
    description: "Filmmaking, photography and commercial video production.",
    longDescription: "A layout built specifically for visual media portfolios. Utilizes overlay grids, lightbox video sliders, category splits, and session booking systems.",
    technologies: ["React", "TypeScript", "Tailwind CSS", "GSAP ScrollTrigger", "Vimeo API"],
    liveUrl: "https://www.marsmediavisualproduction.in/",
    caseStudyUrl: "#",
    mockLayoutType: "photography"
  },
  {
    id: "nightingale-holidays",
    number: "07",
    name: "Nightingale Holidays",
    category: "Travel & Hospitality",
    industry: "Tourism & Bookings",
    description: "Bespoke tour packages, resort bookings and luxury escapes.",
    longDescription: "A highly visual tourism portal displaying scenic locations. Includes tour booking forms, travel blogs, currency calculators, and seasonal package selectors.",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion", "ResortAPI"],
    liveUrl: "https://www.nightingaleholidays.com",
    caseStudyUrl: "#",
    mockLayoutType: "travel"
  },
  {
    id: "verglas-trading",
    number: "08",
    name: "Verglas Trading",
    category: "Supply Chain Portal",
    industry: "Industrial Imports",
    description: "Industrial trading, wholesale supplies & materials logistics.",
    longDescription: "An advanced operations panel displaying live status charts, system logs, deployment pipelines, team roles, and billing history.",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Recharts"],
    liveUrl: "https://www.verglastrading.com",
    caseStudyUrl: "#",
    mockLayoutType: "dashboard"
  },
  {
    id: "smart-wheels",
    number: "09",
    name: "Smart Wheels",
    category: "Automobile Showroom",
    industry: "Automobile & Automotive",
    description: "Premium car dealership, sales, and online test drive booking.",
    longDescription: "A premium car showroom portal featuring interactive spec sheet filters, custom configurator mockups, dealership locators, and financing calculators.",
    technologies: ["Next.js", "Tailwind CSS", "Three.js"],
    liveUrl: "https://www.smartwheelsskating.com/",
    caseStudyUrl: "#",
    mockLayoutType: "automobile"
  },
  {
    id: "idia-interiors",
    number: "10",
    name: "Idia Interiors",
    category: "Interior Architecture",
    industry: "Interior Design",
    description: "Luxury residential space planning and functional decor.",
    longDescription: "A minimalist style portfolio highlighting material textures and light spaces. Features interactive mood boards, catalog sheets, and contact details.",
    technologies: ["React", "Tailwind CSS", "Framer Motion"],
    liveUrl: "https://idiainteriors.in",
    caseStudyUrl: "#",
    mockLayoutType: "interior"
  },
  {
    id: "eastern-hemlock",
    number: "11",
    name: "Eastern Hemlock",
    category: "Timber Supply",
    industry: "Timber & Wood Dubai",
    description: "Importing hardwood, logs & timber products in the UAE.",
    longDescription: "A rustic but modern wooden trade online hub. Includes a visual product catalog list, shipping trackers, wood type configurator, and corporate supplier contacts.",
    technologies: ["React", "Tailwind CSS", "Framer Motion"],
    liveUrl: "https://www.easternhemlock.ae/",
    caseStudyUrl: "#",
    mockLayoutType: "coffee"
  },
  {
    id: "eat-superhuman",
    number: "12",
    name: "Eat Superhuman",
    category: "Organic Food Store",
    industry: "Nutrition & Diet",
    description: "Keto diets, organic meals and healthy meal preparations.",
    longDescription: "A premium restaurant interface focusing on visual food appeal. Integrates fully-interactive digital menus, reservation modules, and automated feedback collection systems.",
    technologies: ["React", "Next.js", "Tailwind CSS", "Zustand"],
    liveUrl: "https://eatsuperhuman.com/",
    caseStudyUrl: "#",
    mockLayoutType: "restaurant"
  }
];
